### ISSUE TITLE
betanyc_businesses add field

### ISSUE THREAD

**Issue by AmandaDoyle** [MODA-NYC/db-recovery-data-partnership#131]
- [ ] Add borocode field

**Comment by mgraber** [comment]
This already exists:
https://github.com/MODA-NYC/db-recovery-data-partnership/blob/a3b308d05bfe81544878f611e57b66cc4ea57792/recipes/betanyc/create.sql#L168-L184

**Comment by AmandaDoyle** [comment]
@mgraber thanks for pointing that out.  The field does not exist in the csv on SharePoint

**Comment by SPTKL** [comment]
https://github.com/MODA-NYC/db-recovery-data-partnership/actions/runs/277114536 <- reran with actions

![image](https://user-images.githubusercontent.com/13207770/94467380-daa38500-0190-11eb-8823-78295056eed7.png)
in sharepoint ^
closing
