### ISSUE TITLE
met/met_attendance_weekly_state

### ISSUE THREAD

**Issue by SPTKL** [MODA-NYC/db-recovery-data-partnership#147]
**met_attendance_weekly_state**
| Input field name | Data Type   | Output field name | Output example |
|------------------|-------------|-------------------|----------------|
| date       | `IYYY-IW` | year_week         | 2020-30     |
| building       | `text` | building         | Fifth Avenue     |
| count       | `int ` | visits         | 10     |
| state       | `text` | state         | OH     |
| country       | `text` | country         | USA     |

**Comment by AmandaDoyle** [comment]
remove `type` and `method` columns from final output

**Comment by SPTKL** [comment]
I think `type` and `method` are actually worth keeping, they characterize user behavior

**Comment by SPTKL** [comment]
46fb7ca
