### ISSUE TITLE
StreetEasy: BK data missing from streeteasy_monthly_rental_sales_index_boro.csv

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#181]
On 12/17, Logan noticed that there is no data with 'borough' = BK in _streeteasy_monthly_rental_sales_index_boro.csv_. In the [source file from StreetEasy](https://streeteasy-market-data-download.s3.amazonaws.com/nta/v2/price_indices-2020-11.csv), there are corresponding fields with 'BOROUGH' = Brooklyn. 

The [2020-12-07](https://nyccityhall.sharepoint.com/:f:/s/RDPDataRepository/EgdtSmMT-hNKmNKgtBFkiwwBaK1j-TyrRNrHNd4Rx9VMVA?e=38VjzB) and [2020-12-16](https://nyccityhall.sharepoint.com/:f:/s/RDPDataRepository/Es8cbIN33GtJngyHz0CvVe8Bz4XzuNSZfFptNm8BymGt2g?e=dIHAB7) uploads appear to be affected.

Please review the script for this dataset to see why Brooklyn data has been dropped.

I would recommend working on this in tandem with #180.

**Comment by SteveScott** [comment]
marking as closed.
