### ISSUE TITLE
Foursquare: replace origin for zip code-level data

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#186]
Zip code level data for Foursquare is shared via Google Drive folder. The four datasets derived from this data, listed below, have not been updated since November because Foursquare moved their data output to a new folder. On 1/8/21, Foursquare shared the [new folder location](https://drive.google.com/drive/u/0/folders/1gydRMonsn_tLwVRUe4CCFMdZ6uOLW0iy) with us.

This folder was only shared with the following accounts: rdp-782@recovery-data-partnership.iam.gserviceaccount.com and nyc.moda.rdp@gmail.com - let me know if you don't have the credentials.

 **For the four zip code-level datasets, please change the origin location to this new folder and push to Sharepoint.**

>Foursquare zip code-level datasets:
> * Daily visits by category by ZIP code (foursquare_daily_zipcode.csv)
> * Average daily visits per week by category by ZIP code (foursquare_weekly_zipcode.csv)
> * Daily visits by category by ZIP code by time of day (foursquare_daily_zipcode_timeofday.csv)
> * Daily visits by category by ZIP code with duration of visit (foursquare_daily_zipcode_raw.csv.zip)

**Comment by SteveScott** [comment]
@objornsson shouldn't be a problem. I will get on it.

**Comment by SteveScott** [comment]
Zipcode data is current.
