### ISSUE TITLE
Source: Live XYZ (private)

### ISSUE THREAD

**Issue by loganwerschky** [MODA-NYC/db-recovery-data-partnership#188]
> # Status
> 
- [x] Data sample received 
- [x] Metadata received
- [x] Data received (Axway)
- [x] Schema finalized
- [x] Final schema implemented
- [x] Metadata written
- [ ] Verify "present" with most recent verification timestamps
- [x] Dataset published

> 
> 
> # Description
> ## Live XYZ Storefront Directory - New York City
> 
> A directory of every storefront on every block in NYC, including historical tracking of turnover, vacancy, and changes to businesses captured from March 2015 to March 2020. Note: Ground survey efforts ended in March 2020.
>  
> Methodology:
>  
> Live XYZ performs storefront mapping through ground surveys.  Every location is mapped in-person at the front door, photographed, classified, and updated with changes over time. This enables tracking and reporting on each location's history of turnover, vacancy, and changes to the business.  The Live team has performed over 1,000,000 ground survey verifications across all 5 boroughs of New York City.
>  
> # Output schema
>
> Live XYZ provides two datasets: (1) snapshot (data as of 3/19/2020) and (2) history (range) from 2015 to 2020.  The same input and output schema applies to both files:
> storefronts_snapshot.csv 
> storefronts_range.csv

Input   Field Name | Input Expected Data Type | Input Required Field | Input Expected  Example | Priority Output Field | Output Field Name | Output Data Type | Output Example | RDP Notes
-- | -- | -- | -- | -- | -- | -- | -- | --
spaceId | Object | Y | 59c10f147b2a3677ef53aedb | Y | spaceid | object | 59c10f147b2a3677ef53aedb |  
validityTime.start | Timestamp | Y | 2018-08-09T19:59:15Z | Y | validitytime_start | YYYY-MM-DD | 2018-08-09 |  
validityTime.end | Timestamp | Y | 2018-08-09T19:59:15Z | Y | validitytime_end | YYYY-MM-DD | 2018-08-09 |  
resolvedName | String | Y | Subway | Y | resolvedname | text | Subway |  
spaceStatus | String | Y | Occupied | Y | spacestatus | text | Occupied |  
placeId | Object | Y | 5511cab237345d0003002b12 | Y | placeid | object | 5511cab237345d0003002b12 |  
name | String | Y if genericName.name is null | Subway | Y | name | test | Subway |  
genericName.id | Object | N | ​5511be5037345d000300062b | Y | genericname_id | object | 59cab4b09a7ab70004666af4 |  
genericName.name | String | N | Hot Dog Cart | Y | genericname_name | text | Jungle Gym |  
placeStatus | String | Y | Permanently Closed | Y | placestatus | text | Permanently Closed |  
operatingBasis | String | Y | Year Round | Y | operatingbasis | text | Year Round |  
chain.chainId | Object | N | 57ba6c57c55a623fd02287f6 | Y | chain_chainid | object | 57ba6c57c55a623fd02287f6 |  
chain.name | String | N | Subway | Y | chain_name | text | Subway |  
address | String | N | 713 Fulton St | Y | address | text | 713 Fulton St |  
postcode | String | N | 11217 | Y | zipcode | text | 11217 |  
hours | Array of hour ranges | N | Sunday 9:00am-9:00pm;Monday 7:00am-10:00pm;Tuesday   7:00am-10:00pm;Wednesday 7:00am-10:00pm;Thursday 7:00am-10:00pm;Friday   7:00am-10:00pm;Saturday 8:00am-10:00pm | M | hours | array text | Sunday 9:00am-9:00pm;Monday   7:00am-10:00pm;Tuesday 7:00am-10:00pm;Wednesday 7:00am-10:00pm;Thursday   7:00am-10:00pm;Friday 7:00am-10:00pm;Saturday 8:00am-10:00pm
urls.website | Array[String] | N | http://local.subway.com/FWPCons/frmSiteMainPage.aspx?CC=USA&LC=ENG&SS=49782-0 | N | urls_website | array text | http://local.subway.com/FWPCons/frmSiteMainPage.aspx?CC=USA&LC=ENG&SS=49782-0
urls.facebook | Array[String] | N | https://www.facebook.com/pages/Subway-Brooklyn/129765290535461 | N | urls_facebook | array text | https://www.facebook.com/pages/Subway-Brooklyn/129765290535461
urls.instagram | Array[String] | N | https://instagram.com/no7restaurant | N | urls_instagram | array text | https://instagram.com/no7restaurant |  
urls.menu | Array[String] | N | http://local.subway.com/FWPCons/frmMenu.aspx?CC=USA&LC=ENG&SS=49782-0&MenuID=35&Dyn=0&PM=preview | N | urls_menu | array text | http://local.subway.com/FWPCons/frmMenu.aspx?CC=USA&LC=ENG&SS=49782-0&MenuID=35&Dyn=0&PM=preview
urls.contact | Array[String] | N | http://www.bukanewyork.com/contact.html | N | urls_contact | array text | http://www.bukanewyork.com/contact.html |  
urls.liveWeb | String | N | https://share.livexyz.com/venue/5511cab237345d0003002b12 | N | urls_liveWeb | array text | https://share.livexyz.com/venue/5511cab237345d0003002b12
slug | String (200 character count limit) | N | Perfect place to smoke your cigars in comfort featuring leather couches,   antique arm-chairs and hand-built, wooden seating areas. | Y | description_short | text | Perfect place to smoke your cigars   in comfort featuring leather couches, antique arm-chairs and hand-built,   wooden seating areas.
description | String (1500 character count limit) | N | Diamante's Brooklyn Cigar Lounge is the perfect place to smoke your   cigars in comfort. Our lounge has ample seating featuring leather couches,   antique arm-chairs and hand-built, wooden seating areas. Diamante's was built   as an extension of your own living room. It's a place where you can enjoy   smoking indoors and relax. Diamante's also has a flat-screen HDTV for viewing   sporting events as well as great music playing in the background. | Y | description_long | text | Diamante's Brooklyn Cigar Lounge is   the perfect place to smoke your cigars in comfort. Our lounge has ample   seating featuring leather couches, antique arm-chairs and hand-built, wooden   seating areas. Diamante's was built as an extension of your own living room.   It's a place where you can enjoy smoking indoors and relax. Diamante's also   has a flat-screen HDTV for viewing sporting events as well as great music   playing in the background.
tagsPrimary.id | Object | Y | 5511be5a37345d000300065a | Y | tagsprimary_id | object | 5511be5a37345d000300065a |  
tagsPrimary.name | String | Y | Sandwich Shop | Y | tagsprimary_name | text | Sandwich Shop |  
subcategoriesPrimary.id | Object | Y | 5511be633d42bd000300064e | Y | subcategoriesprimary_id | object | 5511be633d42bd000300064e |  
subcategoriesPrimary.name | String | Y | Restaurant | Y | subcategoriesprimary_name | text | Restaurant |  
categoriesPrimary.id | Object | Y | 59ea276af86351000446c403 | Y | categoriesprimary_id | object | 59ea276af86351000446c403 |  
categoriesPrimary.name | String | Y | Food | Y | categoriesprimary_name | text | Food |  
tags.id | Array[Object] | Y | 5511be5a37345d000300065a | Y | tags_id | array object | 5511be5a37345d000300065a |  
tags.name | Array[String] | Y | Sandwich Shop | Y | tags_name | array text | Sandwich Shop |  
subcategories.id | Array[Object] | Y | 5511be633d42bd000300064e | Y | subcategories_id | array object | 5511be633d42bd000300064e |  
subcategories.name | Array[String] | Y | Restaurant | Y | subcategories_name | array text | Restaurant |  
categories.id | ​Array[Object] | Y | 59ea276af86351000446c403 | Y | categories_id | array object | 59ea276af86351000446c403 |  
categories.name | ​Array[String] | Y | Food, Drink | Y | categories_name | array text | Food, Drink |  
offerings.positive.id | Array[Object] | N | 563260851f8c100003002b9a,56dc73c2c55a626ccde58419 | Y | offerings_positive_id | array object | 563260851f8c100003002b9a,56dc73c2c55a626ccde58419
offerings.positive.name | Array[String] | N | Quick Bites,Dine In | Y | offerings_positive_name | array text | Quick Bites,Dine In |  
entrances.main.id | Object | Y | 59c10f147b2a3677ef53aeda | Y | entrances_main_id | object | 59c10f147b2a3677ef53aeda |  
entrances.main.lat | Float64 | Y | 40.68743043 | Y | entrances_main_lat | double precision float64 | 40.68743043 |  
entrances.main.lon | Float64 | Y | -73.9769402 | Y | entrances_main_lon | double precision float64 | -73.9769402 |  
entrances.main.floor | Integer | Y | 1 | Y | entrances_main_floor | integer | 1 |  
entrances.main.entranceMethod | String | Y | fixed | Y | entrances_main_entrancemethod | text | fixed |  
entrances.main.origin.type | String | Y | EXTERIOR | Y | entrances_main_origin_type | text | EXTERIOR |  
entrances.main.origin.id |   | Y when entrances.main.origin.type = interior | 59c10f627b2a3677ef549619 | Y | entrances_main_origin_id | object | 59c10f627b2a3677ef549619 | Field not included in Live's    Column Description or Data Dictionary documents
entrances.main.origin.name | String | Y when entrances.main.origin.type = interior | Cuyler Gore Park | Y | entrances_main_origin_name | text | Cuyler Gore Park |  
parent.placeId | Object | N | 5526f8c2d8ca70000300032d | Y | parent_placeid | object | 5526f8c2d8ca70000300032d |  
parent.name | String | N | Cuyler Gore Park | Y | parent_name | text | Cuyler Gore Park |  
isStorefront | Boolean | Y | TRUE | Y | isstorefront | boolean | TRUE |  
isInterior | Boolean | Y | FALSE | Y | isinterior | boolean | FALSE |  
isMobile | Boolean | Y | FALSE | Y | ismobile | boolean | FALSE |  
spaceCreationDate | Timestamp | Y | 2015-03-24T20:36:02Z | Y | spacecreation_date | YYYY-MM-DD | 2015-03-24 |  
placeCreationDate | Timestamp | Y | 2015-03-24T20:36:02Z | Y | placecreation_date | YYYY-MM-DD | 2015-03-24 |  
verifiedTimes | Array[Timestamp] | N | 2018-04-09T17:56:53Z | Y | verifiedtimes | array YYYY-MM-DD | 2018-04-09 |  
verifiedTimesLast | Timestamp | N | 2018-04-09T17:56:53Z | Y | verifiedtimes_last | YYYY-MM-DD | 2018-04-09 |  
  |   |   |   | Y | borough | varchar(2) | BX |  
  |   |   |   | Y | borocode | integer | 2 |  

> Note: it may be advantageous to update the zip-code for all records and eliminate any input that includes more than the 5 digit zip.
>
> # Deliverables
> storefronts_snapshot.csv 
> storefronts_range.csv
>
> # Pipeline
> 
> > this is for source specific processing requirements, tag all sub issues related with this data source for easier status tracking. e.g.
> > 
> > * [ ]  data ingestion #{ issue number here }
> > * [ ]  data transformation #{ issue number here }
> > * [ ]  data export #{ issue number here }
>
> # Use cases
> 
> • Live XYZ Map​ [https://share.livexyz.com](url)
>
> • Department of City Planning:​ ​Assessing Storefront Vacancy in NYC (August 2019) [https://www1.nyc.gov/assets/planning/download/pdf/planning-level/housing-economy/assessing-storefront-vacancy-nyc.pdf](url)
>
> • New York City Comptroller: ​Retail Vacancy in NYC (September 2019) [https://comptroller.nyc.gov/reports/retail-vacancy-in-new-york-city/](url)
>
> • HR&A Advisors: ​Saving Our Retail Corridors Requires Good Data (July 2020) [https://hraadvisors.com/interactive/retail_recovery/](url)
>
> • New York Times: ​‘Who Are We For?’ How the Virus Is Testing the Identity of Chinatown (June 30, 2020) [https://www.nytimes.com/2020/06/30/nyregion/chinatown-coronavirus-nyc.html](url)

**Comment by loganwerschky** [comment]
@objornsson Please take a look at the proposed data schema.  Let me know if you'd like to see it in a different format for analysis.

**Comment by objornsson** [comment]
@loganwerschky 

- Recommend standardization of output names to match other RDP datasets - all lowercase with underscores between words. E.g. spaceCreationDate -> space_creation_date
- I see your note re: entrances.main.origin.id - is this just something we would want to flag for them about their data dictionary?

**Copying over questions from your email - I'll pose these once Axway is sorted out:**
- Frequency of update: While the data includes the verification timestamp, what is their general business practice.  Are there areas of the city that had more frequent verifications than others? Why?
- Interpretation of one line of data: Needs revision/translation. For example, One line of data provides the status of a space (occupied vs unoccupied) and associated business (operating, temporarily closed, coming soon, etc) observed on a specific verification visit.

**Comment by loganwerschky** [comment]
> @objornsson 
>
> **re: Recommend standardization of output names to match other RDP datasets - all lowercase with underscores between words. E.g. spaceCreationDate -> space_creation_date**
> I considered this and we can discuss more offline if productive.
> There are some nomenclature considerations to weigh.  For example, take the following original fields:
> tagsPrimary.id
> tagsPrimary.name
> tags.id
> tags.name
>
> While all four fields start with "tags", the important distinction is noted through the dot.  I'd like to preserve some the nomenclature of the original design -- it is deliberate and makes sense to me generally. My recommendation is to not split "tagsPrimary" with an underscore.  We can change to "tagsprimary_id" but i don not suggest "tags_primary_id".
>
>
> **re: entrances.main.origin.id - is this just something we would want to flag for them about their data dictionary?**
> Let's add to the running list of questions that we can address with the partner after transfer.  I have additional examples beyond this to flag.

**Comment by objornsson** [comment]
Thanks Logan - I was looking for analogs in the current data suite and found 'access_bikepath' and 'concern_notclean' in the USL data - the underscore was used to separate the 'category' and 'unique field name' and the spaces in the unique field name were omitted.

I think my preference might be to retain the dots to separate the category and unique field name, and continue to use underscores to separate words - so tags.primary_id or entrances.main_entrance_method - rather than introducing upper-case, but let me know if you think that's less intuitive.

**Comment by loganwerschky** [comment]
>@objornsson 
> I don't recommend introducing a dot, which is not used in the other data products.  
>
>Following the guidelines outlined by in the wiki here [https://github.com/MODA-NYC/db-recovery-data-partnership/wiki/New-data-pipeline:-guidelines-for-uploading-datasets-to-SFTP](url), and considering the precedents you noted ("access_bikepath", "concern_notclean) as well as other like "dayofweek", I continue to recommend the two following options:
> tagsPrimary.name --> tagsPrimary_name(camelCase and underscore) or tagsprimary_name (underscore only).
>
> Given that there aren't any examples of camelCase in the existing datasets, my preference would be the latter "tagsprimary_name".  
>
> I'll update the table.  We won't finalize the schema until after the transfer.

**Comment by objornsson** [comment]
Sounds good - 'tagsprimary_name' it is.

**Comment by SteveScott** [comment]
Live XYZ has been decomissioned.
