### ISSUE TITLE
The Met: GitHub action failed for latest uploads

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#191]
The Met makes biweekly uploads to two source datasets via [Axway](securetransport.nyc.gov): 'Attendance' and 'Membership.'
The RDP data pipeline turns this into four datasets, [available here](https://nyccityhall.sharepoint.com/sites/RDPDataRepository/SitePages/MET.aspx): 'met_attendance', 'met_attendance_weekly,' 'met_membership,' and 'met_membership_weekly.' 

The latest [scheduled run of the Met action](https://github.com/MODA-NYC/db-recovery-data-partnership/actions/runs/608921262) failed two days ago, and therefore, the Met's two most recent uploads, covering the month of February, are not available on Sharepoint.

Please take a look at why the last run failed, trigger a new run, and make sure that the most recent data is available on Sharepoint.

It would be much appreciated if you could address this **by the end of the week** - let me know if you anticipate that being an issue.

**Comment by SPTKL** [comment]
@objornsson all github actions are failing, just FYI, likely it's cuz the database is full, you might need to add more storage to the database

**Comment by objornsson** [comment]
@SPTKL thank you for the heads-up
