### ISSUE TITLE
Met: change Axway credentials and origin folder 

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#192]
- [x] Change origin folder in Met runner
- [ ] Append missing updates
- [ ] Trigger Met actions 

**3/19 update**
The 'rdpadmin' Axway account now has access to the new _/Met_Museum_2_ folder in Axway, which contains the Met's most recent uploads: _Attendance_20210301to20210314.csv_ and _MembershipTransactions_ao20210314.csv_

The Github actions for the Met are currently running, but they produce empty files. 

The latest updates of the processed datasets on SharePoint include data as of 1/31/2021. While the Memberships data upload files from the Met are cumulative, the Attendance data upload files only cover a two-week period. Therefore, the single attendance file in Axway added to the processed dataset up until now will leave a gap. The 'missing' files (_Attendance_20210201to20210214.csv_ and _Attendance_20210215to20210228.csv_) are available in [this folder on Sharepoint.](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/raw_backups/Met/Attendance?csf=1&web=1&e=5xlQIV) 

**Links:**
- [Axway](https://securetransport.nyc.gov/)
- [Met recipe](https://github.com/MODA-NYC/db-recovery-data-partnership/tree/master/recipes/met)
- [Met actions](https://github.com/MODA-NYC/db-recovery-data-partnership/actions/workflows/met.yml)

**Comment by objornsson** [comment]
updated issue

**Comment by SteveScott** [comment]
@YuliaZamriy may I close this?

**Comment by YuliaZamriy** [comment]
@SteveScott Yep, I'm closing it.
