### ISSUE TITLE
LinkedIn: latest update to Sharepoint

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#193]
- [ ] Trigger LinkedIn actions

**3/19 update:**
The 'rdpadmin' account should have access to the correct folder in Axway - "LinkedIn". There is an updated file titled 'LHR-NYC-Mar2021.xlsx' that includes the monthly update for February 2021 that is not on Sharepoint. I have tried to re-run the LinkedIn action a few times with no success.

**Links:**
- [Axway](https://securetransport.nyc.gov/)
- [LinkedIn recipe](https://github.com/MODA-NYC/db-recovery-data-partnership/tree/master/recipes/linkedin)
- [LinkedIn actions](https://github.com/MODA-NYC/db-recovery-data-partnership/actions/workflows/linkedin.yml)

**Comment by objornsson** [comment]
updated issue

**Comment by SteveScott** [comment]
The LinkedIn action executes without visible errors, but no table is created. The last table created was 2020-09-25

**Comment by objornsson** [comment]
@SteveScott the latest data on Sharepoint shows data that was uploaded by LinkedIn in early February, so I don't think that can be the case

**Comment by SteveScott** [comment]
Is this resolved now?

**Comment by objornsson** [comment]
@SteveScott Yes!
