### ISSUE TITLE
Source: Mastercard (private)

### ISSUE THREAD

**Issue by loganwerschky** [MODA-NYC/db-recovery-data-partnership#196]
> # Status
> 
- [x]  Data sample received
- [x] Metadata received
- [x] Data received
- [x] Schema finalized
- [x] Final schema implemented
- [x] Metadata written
- [x] Dataset published
> 
> 
> # Description
> ## Mastercard -  Retail Location Insights 
> 
> In-store spending statistics indexed and aggregated at the national, state, MSA (New York - Newark - Jersey City), and NYC zip code.
>  
> Methodology:
>  
>Data is produced from in store transactions paid for with a debit, credit, or prepaid gift card on the Mastercard payment network.  Daily data is aggregated from individual retailers to zip codes and are summarized to industries.  The RDP data does not provide detailed industry information. 
>  
> # Output schema
>
>Mastercard provides one dataset: Geogrids_NYC_Zip_Codes_Level_Jan2019_Feb2021.csv
>Note that the end of file name may change with data updates.

Input   Field Name | Input Example | Output Field Name | Output Data Type | Output Example | RDP Notes
-- | -- | -- | -- | -- | --
yr | 2019 | yr | YYYY | 2019 |  
txn_date | 1/6/19 | txn_date | YYYY-MM-DD | 2019-01-06 | change format to match other   date formats in RDP data products
industry | Eating Places | industry | text | Eating Places |  
segment | Domestic | segment | text | Domestic |  
geo_type | State | geo_type | text | State |  
geo_name | New York | geo_name | text | New York |  
nation_name | United States | nation_name | text | United States |  
Zip_code | 10034 | zip_code | text | 10034 |  
txn_amt | 186.66 | txn_amt_index | numeric | 186.66 | e.g., 300 = 3x the average
txn_cnt | 104.48 | txn_cnt_index | numeric | 104.48 | e.g., 100 = average
acct_cnt | 102.88 | acct_cnt_index | numeric | 102.88 | e.g., 25 = 1/4 the average
avg_ticket | 170.16 | avg_ticket_index | numeric | 170.16 |  
avg_freq | 103.61 | avg_freq_index | numeric | 103.61 |  
avg_spend_amt | 178.39 | avg_spend_amt_index | numeric | 178.39 |  
yoy_txn_amt | 101.9 | yoy_txn_amt | numeric | 101.9 | %
yoy_txn_cnt | 41.07 | yoy_txn_cnt | numeric | 41.07 | %
  |   | borough | varchar(2) | MN |  
  |   | borocode | int | 1 |  

>
> # Deliverables
> mastercard_daily_transactions.csv 
>
>
> # Pipeline
> 
> > This is for source specific processing requirements, tag all sub issues related with this data source for easier status tracking. e.g.
> > 
> > * [ ]  data ingestion #{ issue number here }
> > * [x]  data transformation #{ issue number here }
> > * [x]  data export #{ issue number here }
>
>
> # Use Cases and Other Resources
> 
> • Recorded Webinar of Mastercard Retail Location Insights​ platform [(https://go.carto.com/webinars/mastercard-mrli-retail)]

**Comment by loganwerschky** [comment]
@objornsson Suggested immediate next steps:
- [ ] Review schema, esp output data type
- [ ] Confirm data delivery method
- [ ] Confirm data is in one file (some documentation notes "separate files will be generated for each county". This may be out of date.)
- [ ] Complete draft of README

**Comment by SteveScott** [comment]
Waiting for an AWS bucket so we can back-up the data as it comes in.

**Comment by SteveScott** [comment]
Mastercard operational.
