### ISSUE TITLE
Need to add ZIP library to docker image

### ISSUE THREAD

**Issue by SteveScott** [MODA-NYC/db-recovery-data-partnership#207]
Due to memory limitations, we cannot upload the entire Mastercard CSV (400+ MB) to Sharepoint because it must first be in memory. Therefore the Mastercard CSV must be compressed. However, the only format available is gzip, which cannot be opened on Windows without a third party utlility.

We need to add the Zip library to the dev and production docker images to compress to zip format. Alternatively, we need to increase the RAM on the servers to handle larger files.

**Comment by objornsson** [comment]
@SteveScott do we understand how [this recipe](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/recipes/cuebiq/runner_daily.sh) creates a .zip?

**Comment by SteveScott** [comment]
@objornsson Thanks for pointing out this code example. Ok, for some reason zip and unzip are not recognized commands in the terminal, but are recognized when executed inside the script.  The files are zipped now.

**Comment by SteveScott** [comment]
When I execute zip and unzip from the terminal, they are outside the docker image without the zip library installed, while when I execute the program they are inside the docker image that includes the zip library.

**Comment by objornsson** [comment]
@SteveScott we can close this, right?
