### ISSUE TITLE
Foursquare: replace origin for zip-code level data 2

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#226]
Foursquare has moved the source for zip code level data to a [new Google Drive folder](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Fu%2F0%2Ffolders%2F1O0_e1C2Tuu7Mb2kB3KRS6uKyg7LQsxId&data=04%7C01%7COBjornsson%40analytics.nyc.gov%7C381127b121e4451907a908d935c196ff%7C35c828166c56443bbaf68312163cadc1%7C0%7C0%7C637599927872821102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MS2zAMSJ6gU9vLIMrGtCeK5a0w1dVyPv7NWd6nIs9vU%3D&reserved=0), which our two accounts (nyc.moda.rdp@gmail.com and rdp-782@recovery-data-partnership.iam.gserviceaccount.com) have access to. Please replace the origin in the pipelines for the zip code datasets.

See #186 for reference of the previous time this happened.

> Foursquare zip code-level datasets:
> 
> Daily visits by category by ZIP code (foursquare_daily_zipcode.csv)
> Average daily visits per week by category by ZIP code (foursquare_weekly_zipcode.csv)
> Daily visits by category by ZIP code by time of day (foursquare_daily_zipcode_timeofday.csv)
> Daily visits by category by ZIP code with duration of visit (foursquare_daily_zipcode_raw.csv.zip)

**Links:**
- [New Google Drive location](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Fu%2F0%2Ffolders%2F1O0_e1C2Tuu7Mb2kB3KRS6uKyg7LQsxId&data=04%7C01%7COBjornsson%40analytics.nyc.gov%7C381127b121e4451907a908d935c196ff%7C35c828166c56443bbaf68312163cadc1%7C0%7C0%7C637599927872821102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MS2zAMSJ6gU9vLIMrGtCeK5a0w1dVyPv7NWd6nIs9vU%3D&reserved=0)
- [Foursquare recipes](https://github.com/MODA-NYC/db-recovery-data-partnership/tree/master/recipes/foursquare)
- [Foursquare data on Sharepoint](https://nyccityhall.sharepoint.com/sites/RDPDataRepository/foursquare/Forms/AllItems.aspx?viewid=f2dd4c4e%2De00d%2D47a5%2Dba28%2D8f59eed1fb26)

**Comment by SteveScott** [comment]
Fixed by changing environmental variable GDRIVE_FOURSQUARE
