### ISSUE TITLE
LinkedIn pipeline error: Missing optional dependency 'openpyxl'

### ISSUE THREAD

**Issue by YuliaZamriy** [MODA-NYC/db-recovery-data-partnership#230]
**Describe the bug**
LinkedIn pipeline produces a new bug:
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

**Comment by objornsson** [comment]
@YuliaZamriy There is new LinkedIn data as of yesterday, I tried unsuccessfully to trigger the job once it came in.

The new raw data is backed up [here on Sharepoint](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/raw_backups/LinkedIn?csf=1&web=1&e=WZdmhC).

**Comment by YuliaZamriy** [comment]
@objornsson the runner has been offline for a short period of time today because of the changes to the instance I was doing. However, the LinkedIn pipeline has been failing because of a different issue. I made a PR to fix it.
Also, while testing that fix in the dev environment I pushed the data to Sharepoint (our dev environment is not perfect...). So you should see the most recent processed LinkedIn file there alreaday.

**Comment by objornsson** [comment]
Confirming that I see the new processed LinkedIn file - thank you

**Comment by YuliaZamriy** [comment]
Resolved by PR #231
