### ISSUE TITLE
Cuebiq Travellers: storage capacity on EC2 instance needs to be increased

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#232]
Cuebiq Travellers was last updated on [Sharepoint](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/cuebiq/cuebiq_travelers/latest?csf=1&web=1&e=hrfnQz) on 6/30/21 because the EC2 instance is at full storage capacity, so capacity needs to be expanded.

Assigned to @YuliaZamriy at 7/13 tech team meeting.

**Comment by YuliaZamriy** [comment]
@objornsson I increased it to 100G this morning. We'll see if it runs successfully tonight.
