### ISSUE TITLE
Mastercard: proxy error preventing pulls from FTP site

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#233]
The newest Mastercard data on [Sharepoint](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/mastercard/2021-07-13?csf=1&web=1&e=B1Znf1) was last updated on 7/4 because of proxy errors in connecting with Mastercard's FTP site.

As of 7/15, @SteveScott is waiting for a response from DoITT to troubleshoot the proxy issue

When the proxy errors are resolved, we need to check that the entire time series is uploaded to Sharepoint, since the Mastercard pipeline will only pull the latest file.

**Comment by SteveScott** [comment]
resolved by using curl. Required updating the curl library on the EC2 runner and compiling with libssh2 installed. There are a series of edits to the Mastercard file committed directly to the master branch because the problem could not be replicated in the development environment.
