### ISSUE TITLE
 Cuebiq: fix version.txts

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#239]
- [x] Add a version.txt to the ['latest'](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/cuebiq/cuebiq_daily/latest?csf=1&web=1&e=zXafL7) folder in Cuebiq Daily Visits (which otherwise is updating daily as it should)

**Comment by SteveScott** [comment]
Foursquare County is pulling from a public site to get the version number, which is broken.

Cuebiq Daily visits is correctly placing the version into the folder of the run, just not into latest.

**Comment by SteveScott** [comment]
@objornsson Would you please fork the Cuebiq issue as a separate ticket? These issues are not related and I will work on them separately.

**Comment by objornsson** [comment]
Removing Foursquare from this issue and closing since Cuebiq is resolved
