### ISSUE TITLE
Foursquare: investigate county level data lag

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#253]
The most recent Foursquare [zip code data](https://nyccityhall.sharepoint.com/sites/RDPDataRepository/SitePages/Foursquare.aspx) is as of 10/10/21, while the most recent [county data](https://nyccityhall.sharepoint.com/sites/RDPDataRepository/SitePages/Foursquare.aspx) is as of 8/28/21. 

Currently, Foursquare only updates data via .tar.gz files on [Google Drive](https://drive.google.com/file/d/1GkiW2uVB-syZBgXcqtEThNFdJJhDQMbT/view?usp=sharing). Only two accounts have access to this Google Drive - the RDP service account and nyc.moda.rdp @ gmail. 

Can we confirm that these .tar.gz files contain both county- and zip code-level data? If county level data is included, can we investigate why the pipeline is not successfully pulling?

**Comment by SteveScott** [comment]
New data for 10-10 is pulled, extracted, and exiting datacube.

**Comment by objornsson** [comment]
Great - I triggered a manual run and will check back tomorrow to make sure it gets to Sharepoint

**Comment by SteveScott** [comment]
The problem is not in datacube. The problem is in the bash script. I am testing now.

**Comment by SteveScott** [comment]
I disabled the cron job until the issue with foursquare county is resolved. I also made a change so the job will not take hours to run anymore, but will ignore the tables already loaded.
