### ISSUE TITLE
Kinsa: investigate API and nationwide dataset

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#256]
**API access:**
Steve, you should have received an email from Kinsa with a link to activate your API account and attached documentation of the API on 2/17/21. I've forwarded you what Yulia received for your reference, but you may need your own link.

If this link has expired or you're having trouble, please let me know and I can reach out to Kinsa.

**Data frame:** 
Without knowledge of what the API data looks like, below is a basic comparison of what columns the NYC dataset has and what columns a nationwide dataset would need:

| NYC dataset | Nationwide dataset |
| ------------- | ------------- |
| borough  | N/A  |
| borocode | N/A  |
| fips_county | fips_county  |
| date | date  |
| pct_ili | pct_ili  |
| N/A | county |
| N/A | state |

**Comment by SteveScott** [comment]
Thanks for the keys. Will begin shortly.

**Comment by objornsson** [comment]
@SteveScott [Link to Sharepoint 'kinsa/test' folder](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/kinsa/test?csf=1&web=1&e=g0DqrL)

**Comment by SteveScott** [comment]
Working on Kinsa. The National dataset has been found.
