### ISSUE TITLE
LinkedIn: investigate failed runs

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#257]
LinkedIn actions have been failing for the last two-and-a-half weeks, and while I was attributing this to the folder being empty, LinkedIn uploaded data on December 1, so that isn't the issue. Talks with LinkedIn to extend beyond 12/31 are going well (they are currently reviewing a revised legal agreement), so it still makes sense to maintain this pipeline. 

Reading through the log of the action run, it's struggling to create the table - see excerpt below and full log [here](https://github.com/MODA-NYC/db-recovery-data-partnership/runs/4548107451?check_suite_focus=true):
> usr/local/lib/python3.8/site-packages/openpyxl/reader/workbook.py:88: UserWarning: File contains an invalid specification for Metadata. This will be removed
  warn(msg)
/usr/local/lib/python3.8/site-packages/openpyxl/reader/workbook.py:88: UserWarning: File contains an invalid specification for Data. This will be removed
  warn(msg)

Please take a look to see what's triggering this error. If the issue is that the file doesn't look like we expect, let me know and I can forward this along to LinkedIn for future reference.

Given the deletion policies in Axway, this file may be deleted imminently. I've backed it up [here](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/raw_backups/LinkedIn?csf=1&web=1&e=BTxMuM) and can re-upload to Axway if needed.

If there's a need to log-in to Axway through the UI, let me know and I can share credentials.

**Comment by SteveScott** [comment]
#258 
Fixed. Just make sure to manually convert XLSX to CSV. In the future, please request CSV Format. XLSX is no longer compatible.
