### ISSUE TITLE
Mastercard: investigate failed runs

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#261]
For the last two weeks, Mastercard jobs have failed. See links to runs with error codes: [this week](https://github.com/MODA-NYC/db-recovery-data-partnership/actions/runs/1676797682/attempts/1), [last week](https://github.com/MODA-NYC/db-recovery-data-partnership/actions/runs/1648813318/attempts/1). 
In both cases, I have been able to manually re-run the jobs after new data has come in. 

Please review these error codes and take any additional steps you deem helpful to investigate why these runs failed.

The solution could be as simple as changing the cron jobs so that runs are scheduled after weekly updates arrive (Tuesday night/Wednesday would be a safer bet), but this may not be the entire issue.

If it appears that Mastercard has changed their FTP setting back to deleting files after we grab them, we can discuss whether it makes sense to ask them to change it back.

**Comment by SteveScott** [comment]
This is a network issue. The connection is being closed. It is intermittent and can be solved by trying again. It is very hard (and futile) to troubleshoot network failures, and they are out of our control. The best course of action is to re-run the jobs when they fail.

**Comment by objornsson** [comment]
@SteveScott Please reschedule run to Wednesdays

**Comment by SteveScott** [comment]
> @SteveScott Please reschedule run to Wednesdays

Currently they are scheduled to run twice a week. Mondays and Thursdays. Is this sufficient? Which two days would you like it to run? Wednesday and Sunday?

**Comment by objornsson** [comment]
Wednesday and Sunday sounds good. This issue is now a lower priority than the forthcoming Mastercard issue.

**Comment by SteveScott** [comment]
Sometimes runs fail.
