### ISSUE TITLE
Mastercard: dates in file names and historical data check

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#263]
- [x] Change recipe to not create new date folders, but to put all data in _all_data_
- [x] Change recipe to create .csvs instead of .zips
- [x] Change recipe to overwrite in _latest_ folder, referencing version history of Mastercard recipe or other recipes like StreetEasy. Only one file should be in _latest_ folder at one time
- [x] Move new csvs from _latest_ to _all_data_

After this, Andrew to delete files with old naming conventions and delete old date folders.

[Link to Mastercard on Sharepoint](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/mastercard/[latest](https://nyccityhall.sharepoint.com/:f:/r/sites/RDPDataRepository/mastercard/latest?csf=1&web=1&e=2Zzvhv)?csf=1&web=1&e=2Zzvhv)

**Comment by SteveScott** [comment]
The recipe should no longer create new date folders. The format is now unzipped. There is no delete feature in the existing sharepoint code: you can only overwrite with the same filename. This is how StreetEasy does it. The file is now mastercard_latest.csv. This will be placed in the 'Latest' folder.

**Comment by SteveScott** [comment]
CSVs moved from Latest to All_Data
