### ISSUE TITLE
Mastercard: investigate all_data\mastercard_2021-01-01_to_2021-12-31.csv

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#269]
[mastercard_2021-01-01_to_2021-12-31.csv ](https://nycdoitt.sharepoint.com/:x:/r/sites/Cityhall-RDPDataRepository/mastercard/all_data/[mastercard_2021-01-01_to_2021-12-31.csv](https://nycdoitt.sharepoint.com/:x:/r/sites/Cityhall-RDPDataRepository/mastercard/all_data/mastercard_2021-01-01_to_2021-12-31.csv?d=wd5ac46ee095f4b6c830ec4d993235c37&csf=1&web=1&e=elPpU8)?d=wd5ac46ee095f4b6c830ec4d993235c37&csf=1&web=1&e=elPpU8) has the following values of txn_date: 1/1/2021, 1/2/2021, 12/27/2021, 12/28/2021, 12/29/2021, 12/30/2021, and 12/31/2021. 

I think this file is redundant with mastercard_2021-12-27_to_2021-12-31.csv and mastercard_2022-01-01_to_2022-01-02.csv and can be deleted.

- [x] Check to make sure that the data for these days match - in which case, the weird file can be deleted
- [x] Check the original MC data on AWS to see whether or not the dates were transformed

**Comment by SteveScott** [comment]
The issue is in the Mastercard file called Geogrids_NYC_New_Zip_Codes_Level_27_Dec_02_Jan_2022_Final. It is an error on the Mastercard side. You should let them know.

**Comment by SteveScott** [comment]
Also, the data overlaps with known good datasets, so I deleted the bad dataset.
