### ISSUE TITLE
Mastercard: create s3 to Sharepoint pipeline

### ISSUE THREAD

**Issue by objornsson** [MODA-NYC/db-recovery-data-partnership#275]
Build pipeline to sync data in mastercard_processed S3 folder with Sharepoint endpoints (below).

References from Steve on uploading to Sharepoint - [1](https://github.com/MODA-NYC/db-recovery-data-partnership/blob/master/bin/sharepoint.py), [2](https://github.com/NYCMayorOps/ewd-dashboard/blob/main/mastercard/mastercard_upload.py)

Sharepoint endpoints: 
- sync S3 with '[mastercard/all_data](https://nycdoitt.sharepoint.com/:f:/r/sites/Cityhall-RDPDataRepository/mastercard/[all_data](https://nycdoitt.sharepoint.com/:f:/r/sites/Cityhall-RDPDataRepository/mastercard/all_data?csf=1&web=1&e=T54UbM)?csf=1&web=1&e=T54UbM)'
- latest file only in '[mastercard/latest](https://nycdoitt.sharepoint.com/:f:/r/sites/Cityhall-RDPDataRepository/mastercard/[latest](https://nycdoitt.sharepoint.com/:f:/r/sites/Cityhall-RDPDataRepository/mastercard/latest?csf=1&web=1&e=eH1elg)?csf=1&web=1&e=eH1elg)'

**Comment by objornsson** [comment]
@dmontiel-oti to take a look at _borough_ column - values now have single-quotation marks on either side - e.g. 'MN' rather than MN

**Comment by SteveScott** [comment]
[336dd77](https://github.com/MODA-NYC/db-recovery-data-partnership/commit/336dd7756cf218b99d29cf117eaccc92020a87fd)

**Comment by SteveScott** [comment]
#89fa7eba50f112b4fc07551dd62f0c691bf39e6f
