### ISSUE TITLE
Source: Upsolve (private)

### ISSUE THREAD

**Issue by AmandaDoyle** [MODA-NYC/db-recovery-data-partnership#3]
# Status
- [x] Data received
Data received via Google sheet
- [x] Metadata received
Shared via email
- [x] Schema finalized
- [ ] Final schema implemented (Normalization #84)
- [ ] Metadata written

# Description
National personal bankruptcy data.  We'll filter data to just NYC and create aggregations.

# Output schema

##  Table name: upsolve_responses
Individual responses limited to NYC zip codes

| Input field name | Data Type   | Output field name | Output example |
|--------------|-------------|-------------------|----------------|
| NA | 'uuid' | ID | a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11 |
| Interview start time              | `date`    | date               | 2020-06-20     |
| Birth year       | `integer` | birth_year         | 1955     |
| Race: White      | `boolean` | race_white        | 1     |
| Race: Black or African American      | `boolean` | race_black         | 1      |
| Race: Hispanic or Latino American      | `boolean` | race_hispanic | 1      |
| Race: Asian      | `boolean` | race_asian         | 1      |
| Race: Native American      | `boolean` | race_nativeamer         | 1      |
| Gender: Male/Man <br>Gender: Female/Woman  <br>Gender: TransMale/TransMan <br> Gender: TransFemale/TransWoman <br> Gender: Genderqueer/Gender nonconforming  <br>Gender: Something Else         | `text ` | gender        | female      |
| Reason for filing bankruptcy: I lost my job      | `boolean` | r_lostjob               | 1      |
| Reason for filing bankruptcy: My hours or pay was cut at my job      | `boolean` | r_paycut         | 1      |
| Reason for filing bankruptcy: Someone in my family experienced a loss of income | `boolean` | r_familyincome  | 1      |
| Reason for filing bankruptcy: I got sick or injured and could not work | `boolean` | r_injured         | 1      |
| Reason for filing bankruptcy: I received medical bills I cannot pay      | `boolean` | r_medbills         | 1      |
| Reason for filing bankruptcy: I spent money irresponsibly      | `boolean` | r_spending         | 1      |
| Reason for filing bankruptcy: I got behind on other bills (e.g. utilities)      | `boolean` | r_genbills         | 1      |
| Reason for filing bankruptcy: My wages are being garnished      | `boolean` | r_garnishedwages        | 1      |
| Reason for filing bankruptcy: I'm going through a separation or divorce      | `boolean` | r_divorce      | 1      |
| Reason for filing bankruptcy: I'm being evicted or my house is being foreclosed on      | `boolean` | r_housing         | 1      |
| Reason for filing bankruptcy: My car is being repossessed      | `boolean` | r_car         | 1      |
| Reason for filing bankruptcy: Other (please specify)      | `boolean` | r_other         | 1     |
| Other reason for filing bankruptcy      | `text` | r_otherdesc         |   Debt higher than income  |
| Most important reason      | `text` | r_top         |    I lost my job   |
| This reason is related to COVID-19      | `boolean` | r_covid19         | 1      |
| Option tried: Cut back on basic necessities (e.g. groceries, rent, utilities)      | `boolean` | o_gencutback         | 1      |
| Option tried: Stopped paying bills      | `boolean` | o_bills         | 1     |
| Option tried: Sold or pawned things I own      | `boolean` | o_sold         | 1      |
| Option tried: Borrowed money from family and friends      | `boolean` | o_borrowed         | 1      |
| Option tried: Didn't get medical care I needed      | `boolean` | o_nomedcare         | 1      |
| Option tried: Looked for another job or additional income      | `boolean` | o_soughtjob         | 1      |
| Option tried: Debt counseling or debt modification programs      | `boolean` | o_counseling      | 1      |
| Option tried: Negotiated with creditors      | `boolean` | o_negotiated         | 1      |
| Option tried: Talked to a bankruptcy lawyer, but could not afford their fee      | `boolean` | o_lawyer         | 1      |
| What user would have done instead of Upsolve      | `text` | alt_option         | I would not be able to afford filing for bankruptcy     |
| Zip      | `text` | zipcode         | 10011     |
| NA      | `text` | borough         | MN     |
| NA      | `int` | borocode       | 1     |

## Table name: upsolve_weekly_count_by_zip
Number of people filing for bankruptcy by week by zip code for NYC zip codes.  This dataset exists to enable change over time analyses and visualizations 
There is also a shapefile of this dataset.

| Input field name | Data Type   | Output field name | Output example | Description | 
|--------------|-------------|-------------------|----------------|----------------|
| Zip | `text` | zipcode | 10011| The zip code plus week is the unique id.  All zip code should be included even if they don't have bankruptcy cases|
| - | `text` | borough | MN| The borough|
| - | `int` | borough | 1 | The borough's code|
| - | `IYYY-IW` | year_week | 2020-30| The week of the year and the year|
| - | `integer` | total |100|The total number of people who filled out the survey and presumably filed for bankruptcy that week in that zip code|
| - | `integer` | sum_covid |80|The number of people who filled out the survey and said the reason was related to covid19|
| - | `numeric` | per_covid |80|The percentage of people who said the reason was related to covid19|

## Table name: upsolve_sum_by_zip
The running total of people who filled out the survey and presumably filed for bankruptcy in NYC zip codes
There is also a shapefile of this dataset.

| Input field name | Data Type   | Output field name | Output example | Description | 
|--------------|-------------|-------------------|----------------|----------------|
| Zip | `text` | zipcode | 10011| The zip code is the unique id.  All zip code should be included even if they don't have bankruptcy cases|
| - | `text` | borough | MN| The borough|
| - | `int` | borough | 1 | The borough's code|
| - | `integer` | total |100|The running total of people who filled out the survey and presumably filed for bankruptcy|
| - | `integer` | sum_covid |80|The running total of people who filled out the survey and said the reason was related to covid19|
| - | `numeric` | per_covid |80|The percentage of people who said the reason was related to covid19|

# Deliverables
- upsolve_responses.csv
- upsolve_count_by_zip.csv
- ~upsolve_count_by_zip.shp~
- upsolve_sum_by_zip.csv
- upsolve_sum_by_zip.shp

# Pipeline
> this is for source specific processing requirements, tag all sub issues related with this data source for easier status tracking. e.g. 
> - [ ] data ingestion #{ issue number here }
> - [ ] data transformation #{ issue number here }
> - [ ] data export #{ issue number here }

**Comment by SPTKL** [comment]
Should we do a pivot for fields below:

- Race
- Gender
- Reason for filing bankruptcy
- Option tried

So that these columns aren't boolean fields but categorical fields?

**Comment by AmandaDoyle** [comment]
@lseirup Feedback from Lynn for Shapefile it might make more sense to have running total
Questions: What does this dataset tell or not tell you?  Is there the use case for the entire regional area?

**Comment by AmandaDoyle** [comment]
Clarification on outputs added to Deliverables section
