### ISSUE TITLE
ioby: Automate pull from Axway

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#38]
Implemented in #31 

Because there are multiple input tables that can be updated on different frequencies (for example, if one dataset gets re-uploaded to correct it), automating pulls from Axway will require consistent naming and directory structure.

**Comment by SPTKL** [comment]
Maybe something like:
```
- Ioby
	- il4s
	   - iL4s Report for the City of New York-XXXXX.xlsx         
	- ideas
	   - Ideas Report for the City of New York-XXXXXX.xlsx       
	- donation
	   - Donation report for the city of New York_XXXXX.xlsx
	   - Donation Report for the City of New York-XXXXX.xlsx 
```
Naming convention doesn't matter that much because we can rename the files when get do a copy. 
within each folder it's easy for us to get the latest file
although it would be nice if the filenames don't have spaces in them
