### ISSUE TITLE
Source: BetaNYC (public)

### ISSUE THREAD

**Issue by AmandaDoyle** [MODA-NYC/db-recovery-data-partnership#7]
# Status
- [x] Data received
Data are available via GitHub
- [x] Metadata received
- [ ] Schema finalized
- [ ] Final schema implemented (Normalization #78)
- [ ] Metadata written

# Description
o   [North Brooklyn](https://github.com/BetaNYC/open-business-directory/blob/gh-pages/data/rows.csv)
o   [East Village](https://github.com/zhik/whats-open-east-village/blob/gh-pages/data/rows.csv)
o   [Queens (no longer active)](https://github.com/zhik/whos-open-queens/blob/gh-pages/data/rows.csv)
o   [Sunnyside](https://github.com/zhik/whos-open-sunnyside/blob/gh-pages/data/rows.csv)
o   [Uptown Grand Central](https://github.com/zhik/whos-open-uptowngrandcentral/blob/gh-pages/data/rows.csv)

# Output schema

##  Table name: betanyc_businesses
Individual businesses that have been surveyed throughout NYC by BetaNYC to study what and how many businesses are open in different neighborhoods.  Sources are merged into one table and values are normalized.

### Geocoding details
The address provided by BetaNYC will be used to geocode the data.  If the record successfully geocodes the normalized `address`, `zip code`,`borough`, nta values, and lat/long values will come from Geosupport.  If we do not get a hit via Geosupport we take the address and lat/long values from BetaNYC and compute the `zip code`,`borough`, and nta values via a spatial join.

| Input field name uptowngrandcentral|sunnyside| east-village| north brooklyn | Data Type   | Output field name | Output example |
|------------------|------------------| ------------------| ------------------ | ------------------   | ------------------ | ------------------ |
|Name|Name| Name| Name | `text`   | name | Fairway |
| Category |Category| Category| Category | `text`   | category | Food and beverage |
| Sub-Category |Sub-Category| Sub-Category| Sub-Category | `text`   | subcategory | Restaurant or bar |
| Category |Category| Category| Category | `text`   | betanyc_category | Restaurant |
| Sub-Category |Sub-Category| Sub-Category| Sub-Category | `text`   | betanyc_subcategory | bakery;food |
| Phone |Phone| Phone| Phone | `text`   | phone | 718-784-5103 |
| Address | Address | Address | Address | `text`   | address | 2082 Frederick Douglass Boulevard |
| Address | Zipcode | Address | Zip Code | `text`   | zipcode | 10026 |
| NA | NA | NA | NA | `text`   | borough | MN |
| NA | NA | NA | NA | `int`   | borocode | 1 |
| NA | NA | NA | NA | `text`   | ntaname | Central Harlem South |
| NA | NA | NA | NA | `text`   | ntacode | MN11 |
| Status |Status| Status| Status | `text`   | status | Open |
| Pickup Offered |Pickup Offered| Pickup Offered| Pickup Offered | `boolean`   | pickup | yes |
| Delivery Offered | Delivery Offered| Delivery Offered| Delivery Offered | `boolean`   | delivery | yes |
| Hours | Hours | Open Time; Close Time | Hours | `text`   | hours | Fri-Sun: 1pm-7pm |
| Special Accommodation Hours | Special Accommodation Hours | Special Accommodation Hours | Special Accommodation Hours | `text`   | special_hours | Mon-Fri: 8am-9am Senior Hours |
| Black Owned Business | Black Owned Business | Black Owned Business | NA | `boolean`   | black_owned | yes |
| MWBE | MWBE | MWBE | NA | `boolean`   | mwbe | yes |
| Source | Source | Source | Source | `text`   | source | North Brooklyn Neighbors |
| Last Updated | Last Updated | Last Updated | Last Updated | `date`   | last_updated | 2020/07/28 |
| Latitude | Latitude | Latitude | Latitude | `double precision`   | latitude | 40.725038 |
| Longitude | Longitude | Longitude | Longitude | `double precision`   | longitude | -73.956633 |
| NA | NA | NA | NA | `geometry`   | geom | |
| NA | NA | NA | NA | `text`   | geomsource | geosupport |

# Deliverables
betanyc_businesses.csv
betanyc_businesses.shp (point shapefile)

# Pipeline
> this is for source specific processing requirements, tag all sub issues related with this data source for easier status tracking. e.g. 
> - [x] data ingestion #{ issue number here }
> - [ ] data transformation - normalization of attribute values #8 
> - [ ] data export #{ issue number here }

**Comment by objornsson** [comment]
@AmandaDoyle We asked our contact at BetaNYC last Friday to combine the data from their different coalition partners into a single data stream for us. I would recommend de-prioritizing BetaNYC until they do this, unless you think there's helpful prep work that can be done in the meantime.

**Comment by AmandaDoyle** [comment]
@objornsson Lynn connected with Cindy yesterday and communicated that for a sustainable workflow we should just build the pipelines to merge the datasets.  I apologize that this did not get communicated back to you

**Comment by objornsson** [comment]
@AmandaDoyle Roger and no worries - I would rather be the one out of the loop than y'all!

**Comment by objornsson** [comment]
Checked off metadata above since BetaNYC has provided their appendix B - let me know if you need access

**Comment by AmandaDoyle** [comment]
> Checked off metadata above since BetaNYC has provided their appendix B - let me know if you need access

We have this.  Thanks!

**Comment by AmandaDoyle** [comment]
@objornsson did anyone follow-up with BetaNYC on your team to let them know they don't need to do the merging of the dispriate datasets?

**Comment by objornsson** [comment]
@AmandaDoyle Thanks for the reminder - I'm not sure if Cindy has so I just sent an email to be sure

**Comment by objornsson** [comment]
Some questions from reviewing the file you shared a few weeks ago:

1. What does the date in column A (‘v’) refer to? What is the relationship between column A and column U (‘last_updated’)? How will the data updates work (same file, new files, update frequency, etc.)? 
2. Is the term ‘dry retail’ one that is commonly used by DCP / others in the City? It looks like a change that you’ve made rather than a category provided by Beta.
3. There appear to be some duplicate records in the file you shared - example: ‘14th Laundry.’ Is there a reason for this? Should we try to de-duplicate?
4. In column T (‘source’), there are some useful resources like links, but also just some people’s names - example: ‘Katelyn.’ Is this unstandardized column worth keeping / can we scrub the names?

**Comment by SPTKL** [comment]
@objornsson 

### Q1
> What does the date in column A (‘v’) refer to? What is the relationship between column A and column U (‘last_updated’)? How will the data updates work (same file, new files, update frequency, etc.)?

- `v` indicates the date or version of the output table. For example, in the case of `betanyc`, the `v` indicates the date 5 betanyc tables are combined into one by data engineering. 
- `last_updated` is a field coming from source data indicating when a record was last updated.
- **About Updates**: 
   - format: the way we've organized the versioning such that we will generate a new version of the table based on the update frequency and noted by the version field `v`. and there will always be a `latest` tag on the most recently updated version. e.g. 
```
betanyc.2020-08-01
betanyc.2020-08-04
betanyc.latest (which is a copy of betanyc.2020-08-04)
```
So depends on different use cases, a user can either 
1) default to use betanyc.latest (which will be over written over updates)
2) select a snapshot from a specific timestamp (e.g. 2020-08-01)

### Q2
> Is the term ‘dry retail’ one that is commonly used by DCP / others in the City? It looks like a change that you’ve made rather than a category provided by Beta.

Yes, `category` and `subcategory` are created by Data Engineering based categories commonly used by DCP and other agencies. The original `category` and `subcategory` provided by betanyc are renamed to  `betanyc_category` and `betanyc_subcategory` 

### Q3 
(investigating ...)

### Q4 
> In column T (‘source’), there are some useful resources like links, but also just some people’s names - example: ‘Katelyn.’ Is this unstandardized column worth keeping / can we scrub the names?

I think our role is to provide all fields, all data points possible and add enhancements wherever we can. I think decisions like this should be made by the individual users.

**Comment by objornsson** [comment]
@SPTKL Thanks, this is great
