### ISSUE TITLE
Normalization: Foursquare

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#73]
- [x] Change table names to something more descriptive (refer to county/zip rather than foursquare/foursquare_datacube)
- foursquare_daily_county or foursquare_daily_borough
- foursquare_weekly_county or foursquare_weekly_borough
- foursquare_daily_zipcode
- foursquare_weekly_zipcode
- foursquare_daily_zipcode_timeofday
- [x] Only use the grouped data -- the only input records should be those where 
```sql 
categoryid = 'Group'
```
- [x] Remove `state` from foursquare_datacube_grouped 
> (I forget foursquare_datacube_grouped is but no dataset should have state since all of these datasets are for NYC)
- [x] Backfilling  a `borough` field and a `borocode` field using the zipcodes
- [x] Since NYC-only, keep `borough` but remove `county` in foursquare_datacube_grouped (it is empty now)
- [x] Format `date` as `YYYY-MM-DD` in foursquare and foursquare_grouped
- [x] Add borough fields to zipcode level tables
- [x] Create foursquare_daily_zipcode_timeofday and foursquare_daily_zipcode_raw tables

**Comment by AmandaDoyle** [comment]
"categoryname" needs to get changed to "category"

**Comment by SPTKL** [comment]
@AmandaDoyle  @mgraber  
should `day_of_week` be `dayofweek` to be more consistent with `timeofday`?
