### ISSUE TITLE
Normalization: Opportunity Insights

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#77]
- [x] change name to oppinsights_daily_mobility and oppinsights_weekly_mobility
- [x] Map `borough` values to two-character abbreviations in both tables
- [x] Add `borocode` field to both tables
- [x] Clean `county` fields in both tables to create a `county` field and a `state` field` (containing two-character abbreviations
- [x] Change `fipscounty` to `fips_county`

**Comment by SPTKL** [comment]
there's no github action set up for opportunity insight
