### ISSUE TITLE
Normalization: BetaNYC

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#78]
- [x] Add a `borocode` field
- [x] `nta_name` -> `ntaname`, `nta_code` -> `ntacode`
- [x] update `address` so that it just includes house number and street name
- [ ] ~format phone so that parentheses are removed and it just has dashes (i.e. 718-784-5103 and not (718) 784-5103)~
- [x] Output betanyc_businesses.shp which is the point shapefile
- [x] Rename  betanyc.csv to betanyc_businesses.csv

**Comment by SPTKL** [comment]
@AmandaDoyle phone number cleaning is very very hard to do, and it's low value added. it's not a field a user can perform meaningful analysis on

**Comment by AmandaDoyle** [comment]
Borocode needs to be added
