### ISSUE TITLE
installing rdptools

### ISSUE THREAD

**Issue by YuliaZamriy** [MODA-NYC/db-recovery-data-partnership#79]
`pip install rdptools` produces an error:
`Collecting rdptools
  Could not find a version that satisfies the requirement rdptools (from versions: )
No matching distribution found for rdptools
`
Are there particular system requirements to install this package?

**Comment by SPTKL** [comment]
Hi @YuliaZamriy can you log your python version and pip version

**Comment by YuliaZamriy** [comment]
Good catch! `pip3 install rdptools` worked. Thank you!
