### ISSUE TITLE
Normalization: Street Easy

### ISSUE THREAD

**Issue by mgraber** [MODA-NYC/db-recovery-data-partnership#83]
In the NTA dataset:
- [x] Change `nta_name` to `ntaname`
- [x] Change `nta_code` to `ntacode`
- [ ] Change name of dataset to streeteasy_weekly_nta
- [ ] Add borough field

In the rental sales index:
- [ ] Change `month` to `year_month` and format as YYYY-MM
- [ ] Format `borough` as two-character
- [ ] rename to 'streeteasy_monthly_rental_sales_index'

**Comment by AmandaDoyle** [comment]
@SPTKL Can we rename everything from `street_easy` to `streeteasy`?  I realize that might be a large effort, so if it is, leave everything as `street_easy`.
