### ISSUE TITLE
Normalization: Urban System Lab

### ISSUE THREAD

**Issue by AmandaDoyle** [MODA-NYC/db-recovery-data-partnership#95]
- [ ] update `date` to be YYYY-MM-DD format
And what's [here](https://github.com/MODA-NYC/db-recovery-data-partnership/issues/85)

Question:
- [ ] Where are the questions for the Urban System Lab survey?

**Comment by mgraber** [comment]
@AmandaDoyle  Questions are a row in the raw data, a copy of which is on Axway under USL
